services:
  - type: web
    name: busconnect
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build
      cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production